### ISSUE TITLE
Error when loading oligoClasses package: objects ‘open.ff’, ‘close.ff’ are not exported by 'namespace:ff'`

### ISSUE THREAD

**Issue by SergioAlonsoLab** [truecluster/ff#2]
Dear developers,
I'm having problems to install oligoClasses, that depends on ff.
Same problem when trying on Mac OS X 10.14.6 and Linux Debian 10

I tried the standard procedure:
`BiocManager::install("oligoClasses")`

But when trying to load the library, I get the following error:
`Error: package or namespace load failed for ‘oligoClasses’:
 objects ‘open.ff’, ‘close.ff’ are not exported by 'namespace:ff'`

It seems that the problem originates in ff. 
I'm running R version 4.0.2 (2020-06-22) 
In fact, open.ff or close.ff functions are not visible in ff package, despite they appear in the ff package manual. I'm not sure if they should be explicitly visible for oligoClasses to run, or just open and close functions from base are enough.

I'm writing the same question here and in the oligoClasses repository issues tab.
My apologies if the question should not be directed here.

Best regards,
Sergio

**Comment by truecluster** [comment]
Dear Sergio,

oligoClasses break because ff no longer exports S3 methods (calling S3 
methods directly was never recommended). If the generics are called 
everything should work fine:

 > require(ff)
 > packageVersion("ff")
[1] ‘4.0.2’
 > x <- ff(1:10)
 > close(x)
[1] TRUE
 > open(x)
[1] TRUE

Until oligoClasses adapts to this, you might work around by installing 
the old versions of bit,bit64,ff from

https://cran.r-project.org/src/contrib/Archive/bit/bit_1.1-15.2.tar.gz
https://cran.r-project.org/src/contrib/Archive/bit64/bit64_0.9-7.1.tar.gz
https://cran.r-project.org/src/contrib/Archive/ff/ff_2.2-14.tar.gz

Following CRAN guidelines the authors of depending CRAN packages have 
been informed early on about this change. Unfortunately I had not 
bioconductor packages on the radar. Sorry for the inconvenience.

May be there should be a formal way to include bioconductor packages in 
tools::package_dependencies.

Kind regards


Jens Oehlschlägel

**Comment by SergioAlonsoLab** [comment]
Dear Jens,
thank you very much for your prompt response.
I will try to use an older version of ff.
If you don't mind, I will also link your response to the issue that I opened in oligoClasses repository. Perhaps it can help the developers of oligoClasses to adapt this package to the new ff version.
Thanks again,
Sergio

**Comment by SergioAlonsoLab** [comment]
Installation of older versions of bit, bit64 and ff, as suggested by Jens Oehlschlägel, does work.
Hopefully oligoClasses developers will adapt their code to the new ff specifications.
Thank you very much, Jens.
Sergio
